// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameChannelClearingRecord = "channel_clearing_record"

// ChannelClearingRecord mapped from table <channel_clearing_record>
// 当 GORM 生成的 struct 的属性类型带有 *，例如 *string、*int，表示该属性可以为 NULL 值。这是因为数据库中的某些列可以允许存储 NULL 值，而在 Go 语言中，对于普通类型（非指针类型），是无法表示 NULL 值的。因此，GORM 使用指针类型来表示这些属性，使得可以将 NULL 值正确地映射到这些属性中。
type ChannelClearingRecord struct {
	ChannelClearingRecordID         string     `gorm:"column:channel_clearing_record_id;type:varchar(64);primaryKey" json:"channel_clearing_record_id"` // 主键ID
	ChannelID                       string     `gorm:"column:channel_id;type:varchar(16);not null" json:"channel_id"`                                   // 渠道标示
	ChannelDealID                   string     `gorm:"column:channel_deal_id;type:varchar(64);not null" json:"channel_deal_id"`                         // 渠道流水号（渠道订单号）
	ChannelReferenceID              sql.NullString    `gorm:"column:channel_reference_id;type:varchar(64)" json:"channel_reference_id"`                        // 我方流水号（我方送渠道订单号）
	ChannelClearingBatchNo          string     `gorm:"column:channel_clearing_batch_no;type:varchar(64);not null" json:"channel_clearing_batch_no"`     // 批次号channel code + 日期
	Currency                        *string    `gorm:"column:currency;type:varchar(3)" json:"currency"`                                                 // 支付币种
	Amount                          *string    `gorm:"column:amount;type:varchar(64)" json:"amount"`                                                    // 支付金额
	ChannelSettlementCurrency       string     `gorm:"column:channel_settlement_currency;type:varchar(3);not null" json:"channel_settlement_currency"`  // 结算币种
	ChannelSettlementAmount         string     `gorm:"column:channel_settlement_amount;type:varchar(64);not null" json:"channel_settlement_amount"`     // 结算金额
	OrderStatus                     *string    `gorm:"column:order_status;type:varchar(10)" json:"order_status"`
	TransactionType                 string     `gorm:"column:transaction_type;type:varchar(64);not null" json:"transaction_type"`                               // 订单类型，支付，退款，CB，CB win等，渠道映射到我方的类型
	ChannelOrderType                string     `gorm:"column:channel_order_type;type:varchar(64);not null" json:"channel_order_type"`                           // 渠道原始订单类型
	FundsReconciliationPipeID       string     `gorm:"column:funds_reconciliation_pipe_id;type:varchar(64);not null" json:"funds_reconciliation_pipe_id"`       // 资金对账通道
	ClearingReconciliationPipeID    string     `gorm:"column:clearing_reconciliation_pipe_id;type:varchar(64);not null" json:"clearing_reconciliation_pipe_id"` // 清算对账通道
	DoubleEntryFlag                 string     `gorm:"column:double_entry_flag;type:varchar(10);not null" json:"double_entry_flag"`                             // 复式记账，借：credit +，贷：debit  -
	TransactionTime                 *time.Time `gorm:"column:transaction_time;type:datetime" json:"transaction_time"`                                           // 交易时间
	ClearingReconciliationTime      *time.Time `gorm:"column:clearing_reconciliation_time;type:datetime" json:"clearing_reconciliation_time"`                   // 清算对账时间
	CreateTime                      time.Time  `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
	UpdateTime                      time.Time  `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`
	EstimateArriveMinDate           *time.Time `gorm:"column:estimate_arrive_min_date;type:date" json:"estimate_arrive_min_date"`                                       // 预计最小到账日期
	EstimateArriveMaxDate           *time.Time `gorm:"column:estimate_arrive_max_date;type:date" json:"estimate_arrive_max_date"`                                       // 预计最大到账日期
	StatementID                     *string    `gorm:"column:statement_id;type:varchar(64)" json:"statement_id"`                                                        // 我方账单编号
	ClearingReconciliationStatus    *string    `gorm:"column:clearing_reconciliation_status;type:varchar(16)" json:"clearing_reconciliation_status"`                    // 清算对账状态
	FundsReconciliationStatus       *string    `gorm:"column:funds_reconciliation_status;type:varchar(16)" json:"funds_reconciliation_status"`                          // 资金对账状态
	ClearingReconciliationResult    *string    `gorm:"column:clearing_reconciliation_result;type:varchar(64)" json:"clearing_reconciliation_result"`                    // 清算对账结果
	RecordType                      string     `gorm:"column:record_type;type:varchar(32);not null" json:"record_type"`                                                 // 清算类型 收单|外汇
	Remark                          *string    `gorm:"column:remark;type:varchar(1024)" json:"remark"`                                                                  // 摘要
	FundsReconciliationBatch        *string    `gorm:"column:funds_reconciliation_batch;type:varchar(64)" json:"funds_reconciliation_batch"`                            // 资金对账批次号
	IdempotentID                    string     `gorm:"column:idempotent_id;type:varchar(128);not null" json:"idempotent_id"`                                            // 唯一幂等id：文件名+批次号+文件行号
	Notes                           string     `gorm:"column:notes;type:varchar(1024);not null" json:"notes"`                                                           // 备注
	PayoutCode                      string     `gorm:"column:payout_code;type:varchar(16);not null" json:"payout_code"`                                                 // 渠道打款编码，checkout为mcc
	PayoutStatus                    string     `gorm:"column:payout_status;type:varchar(16);not null;default:PAID" json:"payout_status"`                                // 渠道打款状态: PAID已打款 UNPAID未打款
	PayoutDate                      *time.Time `gorm:"column:payout_date;type:date" json:"payout_date"`                                                                 // 渠道打款日期
	ClearingReconcileDetailResultID string     `gorm:"column:clearing_reconcile_detail_result_id;type:varchar(64);not null" json:"clearing_reconcile_detail_result_id"` // 清算对账结果id
	ChannelReconciliationDate       *time.Time `gorm:"column:channel_reconciliation_date;type:date" json:"channel_reconciliation_date"`                                 // 渠道清算时间
	MerchantID                      *string    `gorm:"column:merchant_id;type:varchar(64)" json:"merchant_id"`                                                          // 商户id
	ChannelMerchantID               *string    `gorm:"column:channel_merchant_id;type:varchar(64)" json:"channel_merchant_id"`                                          // 渠道商户id
}

// TableName ChannelClearingRecord's table name
func (*ChannelClearingRecord) TableName() string {
	return TableNameChannelClearingRecord
}
