// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameClearingDiffRecord = "clearing_diff_record"

// ClearingDiffRecord mapped from table <clearing_diff_record>
type ClearingDiffRecord struct {
	ClearingDiffRecordID          string     `gorm:"column:clearing_diff_record_id;type:varchar(64);primaryKey" json:"clearing_diff_record_id"`                 // 清算差异单据编号
	ClearingReconciliationResult  string     `gorm:"column:clearing_reconciliation_result;type:varchar(64);not null" json:"clearing_reconciliation_result"`     // 清算对账结果
	ClearingReconciliationPipeID  string     `gorm:"column:clearing_reconciliation_pipe_id;type:varchar(64);not null" json:"clearing_reconciliation_pipe_id"`   // 清算通道
	TransactionType               string     `gorm:"column:transaction_type;type:varchar(64);not null" json:"transaction_type"`                                 // 支付类型
	OrderTime                     *time.Time `gorm:"column:order_time;type:datetime" json:"order_time"`                                                         // 支付时间
	ChannelReferenceID            *string    `gorm:"column:channel_reference_id;type:varchar(64)" json:"channel_reference_id"`                                  // 我方清算流水号
	ChannelDealID                 string     `gorm:"column:channel_deal_id;type:varchar(64);not null" json:"channel_deal_id"`                                   // 渠道清算流水号
	ClearingRecordAmount          *string    `gorm:"column:clearing_record_amount;type:varchar(64)" json:"clearing_record_amount"`                              // 我方清算金额
	ChannelClearingRecordAmount   string     `gorm:"column:channel_clearing_record_amount;type:varchar(64);not null" json:"channel_clearing_record_amount"`     // 渠道清算金额
	DiffAmount                    string     `gorm:"column:diff_amount;type:varchar(64);not null" json:"diff_amount"`                                           // 差异金额
	ComparisonResult              string     `gorm:"column:comparison_result;type:varchar(32);not null" json:"comparison_result"`                               // 比较结果
	ProcessedAmount               string     `gorm:"column:processed_amount;type:varchar(64);not null" json:"processed_amount"`                                 // 已处理金额
	UnprocessedAmount             string     `gorm:"column:unprocessed_amount;type:varchar(64);not null" json:"unprocessed_amount"`                             // 待处理金额
	ClearingReconciliationBatchID string     `gorm:"column:clearing_reconciliation_batch_id;type:varchar(64);not null" json:"clearing_reconciliation_batch_id"` // 清算对账批次号
	ClearingRecordCurrency        *string    `gorm:"column:clearing_record_currency;type:varchar(64)" json:"clearing_record_currency"`                          // 渠道清算币种
	ChannelClearingRecordCurrency string     `gorm:"column:channel_clearing_record_currency;type:varchar(10);not null" json:"channel_clearing_record_currency"` // 渠道清算币种
	RecordStatus                  string     `gorm:"column:record_status;type:varchar(10);not null" json:"record_status"`                                       // 单据状态
	CreateTime                    time.Time  `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`                                    // 单据生成时间
	FinishedTime                  *string    `gorm:"column:finished_time;type:varchar(64)" json:"finished_time"`                                                // 完结时间
	Operator                      *string    `gorm:"column:operator;type:varchar(64)" json:"operator"`                                                          // 操作员
	Remark                        *string    `gorm:"column:remark;type:varchar(255)" json:"remark"`                                                             // 我方摘要
	Age                           int32      `gorm:"column:age;type:int;not null" json:"age"`                                                                   // 账龄
	AgeLevel                      *string    `gorm:"column:age_level;type:varchar(10)" json:"age_level"`                                                        // 账龄等级
	ChannelID                     *string    `gorm:"column:channel_id;type:varchar(16)" json:"channel_id"`                                                      // 渠道id
	ClearingRecordID              *string    `gorm:"column:clearing_record_id;type:varchar(64)" json:"clearing_record_id"`                                      // 我方流水id
	ChannelClearingRecordID       *string    `gorm:"column:channel_clearing_record_id;type:varchar(64)" json:"channel_clearing_record_id"`                      // 渠道流水id
	UpdateTime                    *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`
}

// TableName ClearingDiffRecord's table name
func (*ClearingDiffRecord) TableName() string {
	return TableNameClearingDiffRecord
}
